/**
 * this file is autogenerated, don't touch
 */

import '../components/footer/footer.component.js'
import '../components/header/header.component.js'
import '../components/banner/banner.component.js'
import '../components/company/company.component.js'
import '../components/slider/slider.component.js'
import '../components/popup/popup.component.js'
